### ISSUE TITLE
iPhone 11 Pro Max layout problems

### ISSUE THREAD

**Issue by GQAdonis** [abuanwar072/Covid-19-Flutter-UI#1]
This application does not render properly on an iPhone 11 Pro Max, which seems to be a problem with every single sample Flutter app I run.  I have attached a screen shot below.

![covid_sample_iphone11_pro_max](https://user-images.githubusercontent.com/100990/79002199-8ee31d80-7b15-11ea-8ec3-23b217769eb4.png)

**Comment by 3lVv0w** [comment]
add 
```
SingleChildScrollView(
        child: )
```
and give some scroll direction horizontal scroll

**Comment by ku4nc4** [comment]
I would suggest either use ```FittedBox``` or ScreenUtil package for dynamic font

**Comment by enricobenedos** [comment]
I've created a dedicated [PR#4](https://github.com/abuanwar072/Covid-19-Flutter-UI/pull/4)
