### ISSUE TITLE
Galaxy Note 10+ rendering issues...

### ISSUE THREAD

**Issue by GQAdonis** [abuanwar072/Covid-19-Flutter-UI#2]
There are also issues running this application on a Galaxy Note 10+.  I have attached a screenshot.

![galaxy_note_covid](https://user-images.githubusercontent.com/100990/79003036-5a706100-7b17-11ea-9b8e-c8d11aae119c.jpg)

**Comment by 3lVv0w** [comment]
add
```
SingleChildScrollView(
        child:  Cloumn( ...
)
```
